version: '3'
services:
  eureka-server:
    build: ./services/eureka-service
    ports:
      - "8761:8761"

  product-service:
    build: ./services/product-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://myrdsinstance-dev.cji4oi0waat8.ap-northeast-2.rds.amazonaws.com:3306/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - eureka-server

  order-service:
    build: ./services/order-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://myrdsinstance-dev.cji4oi0waat8.ap-northeast-2.rds.amazonaws.com:3306/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - eureka-server

  user-service:
    build: ./services/user-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://myrdsinstance-dev.cji4oi0waat8.ap-northeast-2.rds.amazonaws.com:3306/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - eureka-server

  frontend:
    build: ./services/frontend
    ports:
      - "80:80"
    depends_on:
      - product-service
      - order-service
      - user-service

  jenkins:
    build: ./services/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: